project_id = "vwfwtpshwghuonoekwzk"

[functions.bootstrap-admin]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.admin-user-lookup]
verify_jwt = false

[functions.admin-set-role]
verify_jwt = false