project_id = "qwuicyhadpesklhkjxpn"

[functions.bootstrap-admin]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.admin-user-lookup]
verify_jwt = false

[functions.admin-set-role]
verify_jwt = false

[functions.news-fill-images]
verify_jwt = false

[functions.fetch-metadata]
verify_jwt = false